name: Remove pending label on answer

on:
  issue_comment:
    types: [ created ]

jobs:
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name) }}
    name: Remove pending label
    runs-on: ubuntu-latest
    steps:
      - name: removelabel
        uses: siegerts/response@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
           response-label: 'true'
